# Packages
import coreapi
from django.conf import settings
from django.conf.urls import url, include
from rest_framework import renderers
from rest_framework import response
from rest_framework import routers
from rest_framework import schemas
from rest_framework.decorators import api_view, renderer_classes
from rest_framework_swagger.renderers import OpenAPIRenderer
from rest_framework_swagger.renderers import SwaggerUIRenderer
from rest_framework_swagger.views import get_swagger_view

from .view_imgs import ThumbnailViewSet
from .views import PanoramaViewSet


class PanoramaRouter(routers.DefaultRouter):
    """
    Panorama's van Amsterdam
    """

    def get_api_root_view(self, **kwargs):
        view = super().get_api_root_view(**kwargs)
        cls = view.cls

        class Panorama(cls):
            pass

        Panorama.__doc__ = self.__doc__
        return Panorama.as_view()


panorama = routers.DefaultRouter()
panorama.register(r'opnamelocatie', PanoramaViewSet, base_name='panorama')
panorama.register(r'thumbnail', ThumbnailViewSet, base_name='thumbnail')

api_schema = coreapi.Document(title='test Panoramas API', content={})
swagger_schema_view = get_swagger_view(title='Panoramas API')


@api_view()
@renderer_classes([SwaggerUIRenderer, OpenAPIRenderer, renderers.CoreJSONRenderer])
def schema_view(request):
    generator = schemas.SchemaGenerator(title='Panoramas API')
    # crash
    # here we need to add custom schema!
    return response.Response(generator.get_schema(request=request))


@api_view()
@renderer_classes([SwaggerUIRenderer, OpenAPIRenderer, renderers.CoreJSONRenderer])
def schema_view_test(request):
    # here we need to add custom schema!
    return response.Response(api_schema)


urlpatterns = [
    url(r'^panorama/', include(panorama.urls)),
    url(r'^status/', include('health.urls')),

    # Initial autogenerated schema. Can de retrieved on /_swagger/?format=openapi
    url(r'^_swagger/?$', schema_view),
    url(r'^_swagger2/?$', swagger_schema_view),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
